skyco/apps/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import signup

app_name = 'users'
urlpatterns = [
    url(r'^signup/$', signup, name='signup'),

    url(r'^login/$', auth_views.login, {'template_name': 'auth/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

skyco/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from rest_framework import routers
from skyco.apps.operations.views import ACMIRequestAPI, ACMIResponseAPI, SummaryAPIViewset
from skyco.apps.contracts.views import ContactViewset
from skyco.apps.users.views import CompanyViewSet, UserViewSet


router = routers.DefaultRouter(trailing_slash=False)
router.register(r'requests', ACMIRequestAPI)
router.register(r'responses', ACMIResponseAPI)
router.register(r'summary', SummaryAPIViewset, base_name='summary')
router.register(r'contracts', ContactViewset)
router.register(r'company', CompanyViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^api/v1/', include(router.urls)),
    url(r'^auth/', include('rest_auth.urls')),
    url(r'^registration/', include('rest_auth.registration.urls')),
    # url(r'^', include('skyco.apps.users.urls'), name='users'),
    # url(r'^', include('skyco.apps.operations.urls'), name='operations'),
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
]

skyco/apps/operations/models.py
from django.utils import timezone
from django.db import models

from skyco.apps.users.models import Company, User
from skyco.apps.operations.exceptions import RequestHasAcceptedResponse, ResponseAcceptedException


class Airport(models.Model):
    code = models.CharField(max_length=4)

    def __str__(self):
        return '{}'.format(self.code)


class PlaneType:
    ANY = 'ANY'
    A320 = 'A320'
    PLANE_TYPE_CHOICES = (
        (ANY, 'Any'),
        (A320, 'Airbus 320'),
    )


class Plane(models.Model):
    model = models.CharField(choices=PlaneType.PLANE_TYPE_CHOICES, max_length=50, blank=False)
    registration_id = models.CharField(max_length=15, blank=False)
    operator = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.model)


class ACMIRequestManager(models.Manager):

    def personal(self, user):
        """
        Return the personal ACMI requests of this user
        """
        return self.filter(user=user, deleted=False)


class ACMIRequest(models.Model):
    objects = ACMIRequestManager()
    # Request details
    plane = models.CharField(choices=PlaneType.PLANE_TYPE_CHOICES, max_length=50, blank=True)
    active = models.BooleanField(default=True)

    # Relationships
    user = models.ForeignKey(User, related_name='requests', on_delete=models.PROTECT)

    # Timing details
    expires_at = models.DateTimeField(null=True)

    deleted = models.BooleanField(default=False)
    deleted_at = models.DateTimeField(null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    viewed_at = models.DateTimeField(null=True)

    def __str__(self):
        return 'ACMI Request {}'.format(self.pk)

    def __unicode__(self):
        return

    def accept_response(self, response_instance: 'ACMIResponse'):
        response_instance.accepted = True
        return response_instance.save(update_fields=['accepted'])

    def mark_deleted(self):
        if self.responses.filter(accepted=True):
            raise RequestHasAcceptedResponse
        self.deleted = True
        self.deleted_at = timezone.now()
        self.save(update_fields=['deleted', 'deleted_at'])


class ACMIResponseManager(models.Manager):

    def to_personal_requests(self, user):
        return self.filter(acmi_request__user=user)


class ACMIResponse(models.Model):
    objects = ACMIResponseManager()
    # Response details
    price_block_hour = models.FloatField(help_text='Price per block hour')
    daily_allowance = models.FloatField(help_text='Per diem')
    min_block_hour = models.FloatField(help_text='Minimum block hour amount')
    plane = models.CharField(max_length=50, blank=False)
    early_payment = models.BooleanField(default=False)
    base = models.CharField(max_length=50)
    accepted = models.BooleanField(default=False)

    # Relationships
    acmi_request = models.ForeignKey(ACMIRequest, related_name='responses', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='responses', on_delete=models.PROTECT)
    contract = models.ForeignKey('Contract', related_name='responses', on_delete=models.PROTECT)

    deleted = models.BooleanField(default=False)
    deleted_at = models.DateTimeField(null=True)

    # Timing details
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    viewed_at = models.DateTimeField(null=True)

    def mark_deleted(self):
        if self.accepted:
            raise ResponseAcceptedException
        self.deleted = True
        self.deleted_at = timezone.now()
        self.save(update_fields=['deleted', 'deleted_at'])


class RouteType:
    LIVE = 'LIVE'
    FERRY = 'FERRY'
    ROUTE_TYPE_CHOICES = (
        (LIVE, 'live'),
        (FERRY, 'ferry'),
    )


class Route(models.Model):
    # Flight details
    departure = models.CharField(max_length=10, null=False)
    arrival = models.CharField(max_length=10, null=False)
    departure_at = models.DateTimeField()
    arrival_at = models.DateTimeField()
    passenger_number = models.IntegerField(null=False, help_text='PAX')
    call_sign = models.CharField(max_length=20, null=True)
    type = models.CharField(choices=RouteType.ROUTE_TYPE_CHOICES, max_length=50, blank=False, default=RouteType.LIVE)

    # Relationships
    acmi_request = models.ForeignKey(ACMIRequest, null=True, related_name='routes', on_delete=models.CASCADE)
    acmi_response = models.ForeignKey(ACMIResponse, null=True, related_name='routes', on_delete=models.CASCADE)

    # Timing details
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{departure} to {arrival}'.format(departure=self.departure, arrival=self.arrival)


class Contract(models.Model):
    name = models.CharField(max_length=30, blank=False)
    default_conditions = models.TextField(editable=False, default='Default contract text and conditions')
    additional_conditions = models.TextField()

    # Relationships
    user = models.ForeignKey(User, null=False, related_name='contracts', on_delete=models.CASCADE)

    # Timing details
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

skyco/apps/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from skyco.apps.users.models import User


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', )

skyco/apps/contracts/views.py
from rest_framework import viewsets, permissions
from skyco.apps.operations.models import Contract
from skyco.apps.contracts.serializers import ContractSerializer


class ContactViewset(viewsets.ModelViewSet):
    model = Contract
    queryset = Contract.objects.none()
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = ContractSerializer

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

skyco/apps/operations/views.py
from django.views import generic
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from rest_framework import status
from rest_framework.viewsets import ModelViewSet, ViewSet
from rest_framework.exceptions import ValidationError
from rest_framework.response import Response
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from skyco.apps.core.rest_framework.fields import EpochJSDateField


from skyco.apps.operations.exceptions import RequestHasAcceptedResponse
from skyco.apps.operations.models import ACMIRequest, ACMIResponse
from skyco.apps.operations.serializers import ACMIRequestSerializer, ACMIResponseSerializer


class ACMIRequestListView(generic.ListView):
    model = ACMIRequest
    template_name = 'operations/requests_list.html'
    context_object_name = 'recent_requests'

    def get_queryset(self):
        """Return the last five published questions."""
        return ACMIRequest.objects.all()


class ACMIRequestCreateView(CreateView):
    model = ACMIRequest
    fields = []

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class ACMIRequestDetailView(DetailView):
    model = ACMIRequest
    template = 'operations/acmirequest_detail.html'


# def index(request):
#     recent_requests = ACMIRequest.objects.filter(active=True)
#     context = {
#         'recent_requests': recent_requests
#     }
#     return render(request, 'acmi_request_list.html', context)


class ACMIRequestAPI(ModelViewSet):
    model = ACMIRequest
    queryset = ACMIRequest.objects.all()
    serializer_class = ACMIRequestSerializer
    permission_classes = (IsAuthenticated,)

    # TODO: Allow users to view requests only that are not theirs. /
    # Personal requests are different.

    def list(self, request, *args, **kwargs):
        queryset = ACMIRequest.objects.exclude(user=self.request.user)
        return Response(data=self.serializer_class(queryset, many=True).data)

    @action(methods=['get'], detail=False, url_path='personal', url_name='personal')
    def personal(self, request):
        queryset = self.queryset.filter(user=self.request.user, deleted=False)
        serializer = self.serializer_class(queryset, many=True)
        return Response(data=serializer.data, content_type='json')

    @action(methods=['get'], detail=True, url_path='responses', url_name='requests-responses')
    def responses(self, request, pk):
        acmi_request = self.get_object()
        if acmi_request.user != request.user:
            raise ValidationError('You can only see responses to your own requests.')
        serializer = ACMIResponseSerializer(acmi_request.responses.all(), many=True)
        return Response(data=serializer.data)

    @action(methods=['post'], detail=True, url_path='accept', url_name='requests-accept-response')
    def accept(self, request, pk):
        acmi_request = self.get_object()
        if acmi_request.user != request.user:
            raise ValidationError('You can not accept responses to your own requests.')
        acmi_response = request.data.get('acmi_response', None)
        if not acmi_response:
            raise ValidationError('ACMI Response id is missing.')
        acmi_response = ACMIResponse.objects.get(pk=acmi_response)
        acmi_request.accept_response(acmi_response)
        return Response(status=status.HTTP_200_OK)

    def perform_destroy(self, instance):
        try:
            instance.mark_deleted()
        except RequestHasAcceptedResponse as e:
            raise ValidationError(e.message)


class ACMIResponseAPI(ModelViewSet):
    model = ACMIResponse
    queryset = ACMIResponse.objects.all()
    serializer_class = ACMIResponseSerializer
    permission_classes = (IsAuthenticated,)

    def perform_delete(self, instance):
        instance.mark_deleted()

    @action(methods=['get'], detail=False, url_path='personal', url_name='personal')
    def personal(self, request):
        queryset = self.queryset.filter(user=self.request.user)
        serializer = self.serializer_class(queryset, many=True)
        return Response(data=serializer.data, content_type='json')

    @action(methods=['post'], detail=True, url_path='accept', url_name='response-accept')
    def accept(self, request, pk):
        acmi_response = self.get_object()
        if acmi_response.user == request.user:
            raise ValidationError('You can not accept responses to your own requests.')
        acmi_request = request.data.get('acmi_request', None)
        if not acmi_request:
            raise ValidationError('ACMI Request id is missing.')

        acmi_request = ACMIRequest.objects.get(pk=acmi_request)
        if acmi_request.responses.filter(accepted=True):
            raise ValidationError('You have already accepted a response to this request.')
        acmi_request.accept_response(acmi_response)
        return Response(data={'message': 'You have successfully accepted the response'}, status=status.HTTP_200_OK)

    @action(methods=['post'], detail=True, url_path='update', url_name='response-update')
    def update_response(self, request, pk):
        acmi_response = self.get_object()

        viewed_at = request.data.get('viewed_at')
        previous_response_count = request.data.get('previous_response_count')

        fields_to_update = []

        if viewed_at:
            acmi_response.viewed_at = EpochJSDateField().to_internal_value(viewed_at)
            fields_to_update.append('viewed_at')

        if previous_response_count:
            acmi_response.previous_response_count = previous_response_count
            fields_to_update.append('previous_response_count')

        if fields_to_update:
            acmi_response.save(update_fields=fields_to_update)
            serializer = self.serializer_class(acmi_response)
            return Response(data=serializer.data)
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST)


class SummaryAPIViewset(ViewSet):
    permission_classes = (IsAuthenticated,)

    def list(self, request):
        epoch_converter = EpochJSDateField()
        responses_counter = self.get_personal_request_responses_count(request)
        latest_request_date = epoch_converter.to_representation(self.get_latest_request_date(request))
        latest_response_date = epoch_converter.to_representation(self.get_latest_response_date(request))
        # TODO: Implement latest message for this user method property.
        # latest_message_date = self.get_latest_message_date(request)
        return Response(data={
            'responses_counter': responses_counter,
            'latest_request_date': latest_request_date,
            'latest_response_date': latest_response_date,
        })

    def get_latest_request_date(self, request):
        newest_request = ACMIRequest.objects.exclude(user=request.user)
        if not newest_request.count():
            return None
        return newest_request.last().created_at

    def get_personal_request_responses_count(self, request):
        acmi_requests = ACMIRequest.objects.personal(user=request.user).filter(active=True)
        responses_counter = 0
        for personal_request in acmi_requests:
            responses_counter += personal_request.responses.count()
        return responses_counter

    def get_latest_response_date(self, request):
        responses_to_personal_requests = ACMIResponse.objects.to_personal_requests(user=request.user)
        if not responses_to_personal_requests.count():
            return None
        return responses_to_personal_requests.last().created_at

    # TODO: Implement latest messages date
    # def get_latest_message_date(self, request):
    #     messages = Messages.objects.filter(user=request.user)
    #     if not messages:
    #         return None
    #     return messages.last().created_at

skyco/apps/users/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from rest_framework.response import Response
from rest_framework import permissions, viewsets, mixins
from rest_framework.decorators import action

from skyco.apps.users.models import Company, User
from skyco.apps.users.forms import SignUpForm
from skyco.apps.users.serializers import CompanySerializer, UserSerializer


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'auth/signup.html', {'form': form})


class CompanyViewSet(viewsets.ModelViewSet):

    model = Company
    queryset = model.objects.none()
    serializer_class = CompanySerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return Company.objects.filter(user=self.request.user.pk)

    def update(self, request, *args, **kwargs):
        import ipdb; ipdb.set_trace()
        return super().update(request, *args, **kwargs)

    @action(methods=['get'], detail=False, url_name='me', url_path='me')
    def me(self, request, *args, **kwargs):
        company_serializer = self.serializer_class(self.get_queryset().first())
        return Response(company_serializer.data)


class UserViewSet(viewsets.ReadOnlyModelViewSet, mixins.UpdateModelMixin):
    model = User
    serializer_class = UserSerializer
    queryset = model.objects.none()
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return self.model.objects.get(pk=self.request.user.pk)

    @action(methods=['get'], detail=False, url_name='me', url_path='me')
    def me(self, request, *args, **kwargs):
        user_serializer = self.serializer_class(self.get_queryset())
        return Response(user_serializer.data)

skyco/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="/static/dashboard.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="/">
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  Your requests
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  Schedule
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Other</span>
              <a class="d-flex align-items-center text-muted" href="#">
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  Settings
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">
                  Logout
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="row">
            <div class="col">
              <p class="page-title">Dashboard</p>
              <p class="page-subtitle">Here you can find incoming requests from others and check requests you made.</p>
            </div>
          </div>
          {% block content %}
          {% endblock %}
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">

              <h1 class="h2">Dashboard</h1>
              <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group mr-2">
                  <button class="btn btn-sm btn-outline-secondary">Share</button>
                  <button class="btn btn-sm btn-outline-secondary">Export</button>
                </div>
                <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                  <span data-feather="calendar"></span>
                  This week
                </button>
              </div>
          </div>
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>
    {% block custom_javascript %}
    {% endblock %}
  </body>
</html>